Sprint 1  feat/sign in sign up
SkarabeyDM/graphiql-app pull request #29
Opened 2024-08-25 09:25 UTC by mikhaelHan

## Описание изменений 📝
Подключён Firebase
Добавлены 2 компонента "login" и "registration" 
Добавлен компонент "alert" для визуализации аутентификации. 
Добавлен redux для работы с компонентом "alert".
Реализовано покрытие кода тестами.

## Проверка изменений 🔍
Открыть приложение

## Обоснование изменений 💡
Это необходимо по требованием финального задания

## Чеклист ✅

- [ ] Добавил комментарии к коду TODO где необходимо вставить навигацию
- [ ] Внес соответствующие изменения в документацию
- [ ] Мои изменения не генерируют новых предупреждений
- [ ] Добавил тесты, которые доказывают, что мое исправление эффективно или что моя функция работает

## Особые замечания для вашего рецензента ❗
Компонент Authorisation по сути не нужен. Он для визуального представления компонентов login и registration

## Скриншот 📷
![image](https://github.com/user-attachments/assets/06bc5cd0-7d97-4c20-a80f-9d6530033052)

## Issues

close ...

2024-08-26 06:08 UTC, SkarabeyDM requested changes

2024-08-26 06:08 UTC, SkarabeyDM commented on src/widgets/alert/Alert.component.tsx
> +      }}
Инлайновые стили пишем через свойство `sx`
```suggestion
      sx={{
        transitionDuration: '0.3s',
        opacity: alert.alertState.alert ? '1' : '0',
      }}
```

2024-08-26 06:08 UTC, SkarabeyDM commented on src/widgets/authorization/Authorisation.component.tsx
> +  );
```suggestion
    <Box display="flex" flexDirection="column" gap="2rem" marginTop="2rem">
      <Provider store={store}>
        <AlertComponent />
        <Box component="div" display="flex" gap="5rem">
          <RegistrationComponent />
          <LoginComponent />
        </Box>
      </Provider>
    </Box>
```

2024-08-26 06:10 UTC, SkarabeyDM commented on src/widgets/authorization/Authorisation.component.tsx
> +    </div>
```suggestion
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: '2rem',
        marginTop: '2rem',
      }}
    >
      <Provider store={store}>
        <AlertComponent />
        <Box component="div" display="flex" gap="5rem">
          <RegistrationComponent />
          <LoginComponent />
        </Box>
      </Provider>
    </div>
```

2024-08-26 06:42 UTC, SkarabeyDM commented
Убери из названий всех компонентов слово `Component`, оно лишнее, как и `.component` в названиях файлов. А сами компоненты помести в слайс `ui` соответствующего им сегмента, например: `widgets/authorisation/Login.component.tsx` => `widgets/authorisation/ui/Login.tsx` и т.д.
И добавь файл реекспорта (`index.ts`) в каждый сегмент, чтобы все компоненты можно было прям из него импортировать:
`import { Login, Registration, Authorisation } from '@widgets/authorisation'`

2024-08-26 06:44 UTC, SkarabeyDM requested changes

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Login.component.tsx
> +        <Box component="div" position="relative">
```suggestion
        <Box position="relative">
```

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Login.component.tsx
> +            component="div"
```suggestion
          <Box
```

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Login.component.tsx
> +        <Box component="div" position="relative">
```suggestion
        <Box position="relative">
```

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Login.component.tsx
> +            component="div"
```suggestion
          <Box
```

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Login.component.tsx
> +            component="div"
```suggestion
```

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Login.component.tsx
> +        <Box component="div" display="flex" justifyContent="space-between">
```suggestion
        <Box display="flex" justifyContent="space-between">
```

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Registration.component.tsx
> +        <Box component="div" position="relative">
```suggestion
        <Box position="relative">
```

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Registration.component.tsx
> +            component="div"
```suggestion
```

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Registration.component.tsx
> +        <Box component="div" position="relative">
```suggestion
        <Box position="relative">
```

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Registration.component.tsx
> +            component="div"
```suggestion
```

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Registration.component.tsx
> +            component="div"
```suggestion
```

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Registration.component.tsx
> +        <Box component="div" position="relative">
```suggestion
        <Box position="relative">
```

2024-08-26 06:44 UTC, SkarabeyDM commented on src/widgets/authorization/Login.component.tsx
> +          </IconButton>
Этот кусок кода повторяется 4 раза. Сделай из него отдельный компонент `<VisibilityButton>` в слайсе `shared/ui` и замени во всех инпутах паролей

2024-08-26 06:49 UTC, SkarabeyDM commented on src/widgets/authorization/Registration.component.tsx
> +          </IconButton>
Зачем в форме логина подтверждение пароля?
```suggestion
```

2024-08-26 16:53 UTC, mikhaelHan commented on src/widgets/alert/Alert.component.tsx
> +      }}
fixed it

2024-08-26 16:53 UTC, mikhaelHan commented on src/widgets/authorization/Authorisation.component.tsx
> +    </div>
fixed it

2024-08-26 16:54 UTC, mikhaelHan commented on src/widgets/authorization/Login.component.tsx
> +        <Box component="div" position="relative">
fixed it

2024-08-26 16:54 UTC, mikhaelHan commented on src/widgets/authorization/Login.component.tsx
> +            component="div"
fixed it

2024-08-26 16:55 UTC, mikhaelHan commented on src/widgets/authorization/Login.component.tsx
> +        <Box component="div" position="relative">
fixed it

2024-08-26 16:55 UTC, mikhaelHan commented on src/widgets/authorization/Login.component.tsx
> +            component="div"
fixed it

2024-08-26 16:55 UTC, mikhaelHan commented on src/widgets/authorization/Login.component.tsx
> +            component="div"
fixed it

2024-08-26 16:55 UTC, mikhaelHan commented on src/widgets/authorization/Login.component.tsx
> +        <Box component="div" display="flex" justifyContent="space-between">
fixed it

2024-08-26 16:55 UTC, mikhaelHan commented on src/widgets/authorization/Registration.component.tsx
> +        <Box component="div" position="relative">
fixed it

2024-08-26 16:55 UTC, mikhaelHan commented on src/widgets/authorization/Registration.component.tsx
> +            component="div"
fixed it

2024-08-26 16:55 UTC, mikhaelHan commented on src/widgets/authorization/Registration.component.tsx
> +        <Box component="div" position="relative">
fixed it

2024-08-26 16:55 UTC, mikhaelHan commented on src/widgets/authorization/Registration.component.tsx
> +            component="div"
fixed it

2024-08-26 16:55 UTC, mikhaelHan commented on src/widgets/authorization/Registration.component.tsx
> +            component="div"
fixed it

2024-08-26 16:56 UTC, mikhaelHan commented on src/widgets/authorization/Registration.component.tsx
> +        <Box component="div" position="relative">
fixed it

2024-08-26 16:56 UTC, mikhaelHan commented on src/widgets/authorization/Login.component.tsx
> +          </IconButton>
fixed it

2024-08-26 16:56 UTC, mikhaelHan commented on src/widgets/authorization/Registration.component.tsx
> +          </IconButton>
fixed it

2024-08-26 16:57 UTC, mikhaelHan commented
fixed everything

2024-08-27 06:41 UTC, SkarabeyDM approved these changes

2024-08-27 10:07 UTC, merged