Sprint 2  feat/rest full client
SkarabeyDM/graphiql-app pull request #41
Opened 2024-09-05 18:39 UTC by mikhaelHan

## Описание изменений 📝
Добавлен компонент RestFullClient, также добавлено покрытие тестами.

## Проверка изменений 🔍
Импортировать и зарендерить компонент в страницу "RestFullClient page"

## Обоснование изменений 💡
Этого требует ТЗ

## Чеклист ✅

- [ ] Добавил комментарии к коду в труднодоступных для понимания областях
- [ ] Внес соответствующие изменения в документацию
- [ ] Мои изменения не генерируют новых предупреждений
- [ ] Добавил тесты, которые доказывают, что мое исправление эффективно или что моя функция работает

## Скриншот 📷
![image](https://github.com/user-attachments/assets/2253c962-8680-4f1b-afae-8798b25d340a)
![image](https://github.com/user-attachments/assets/6096444c-f437-4834-9a15-7928c2a20391)
![image](https://github.com/user-attachments/assets/4432ae5c-dcd7-43f5-a656-c12e55bb69ae)
![image](https://github.com/user-attachments/assets/8a4e413d-67ea-422c-a2ae-f5a714800933)

close #36

2024-09-06 09:21 UTC, imdimasan commented on next.config.mjs
> +};
Это обязательно?

2024-09-06 09:21 UTC, imdimasan commented on src/pages/HomePage/ui/HomePage.tsx
> +      <Grid></Grid>
Зачем это тут если нет внутри ничего?

2024-09-06 09:21 UTC, imdimasan commented on src/pages/HomePage/ui/HomePage.tsx
>  const HomePageComponent = () => {
Не нужно лепить длинные названия, когда и так понятно. Лучше разруливать правильно архитектурой папок и файлов.

```suggestion
const HomePage = () => {
```

У вас же TS? :)

```suggestion
const HomePageComponent: FC = () => {
```

Если есть пропсы:
```suggestion
const HomePageComponent: FC<IHomePageComponent> = () => {
```

Если пейджа:
```suggestion
const HomePageComponent: NextPage = () => {
```

Если пейджа с пропсами:
```suggestion
const HomePageComponent: NextPage<IHomePageComponent> = () => {
```

2024-09-06 09:21 UTC, imdimasan commented on src/shared/tests/__tests__/BodyManager.test.tsx
> +describe('BodyManager component', () => {
Если тестов много то описывайте JSDoc-ами что он делает и что должно произойти, чтобы следующему разработчику было максимально быстро понятно что тут подается и что должно быть в итоге

/**
* Test for ..... bla bla bla
*/

2024-09-06 09:21 UTC, imdimasan commented on src/shared/tests/__tests__/HeaderManager.test.tsx
> +describe('HeaderManager component', () => {
Тоже самое, хорошим тоном добавлять JSDoc

2024-09-06 09:21 UTC, imdimasan commented on src/shared/tests/__tests__/MethodManager.test.tsx
> +describe('MethodManager component', () => {
JSDoc

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/model/bodyManagerModel.ts
> +  setBody: (value: (prev: IBodyData | null) => IBodyData | null) => void;
Для useState другие типы
https://stackoverflow.com/questions/71324797/react-typescript-what-does-dispatchsetstateactionboolean-stand-for
https://medium.com/ableneo/typing-of-react-hooks-in-typescript-947b200fa0b0

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/model/headerManagerModel.ts
> +  setHeaders: (value: IHeaderData) => void;
Типы для setState

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/model/headerManagerModel.ts
> +  setItems: (value: (prev: IHeaderItem[]) => IHeaderItem[]) => void;
Типы для setState

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/model/methodManagerModel.ts
> +  setMethod: (value: ICRUD) => void;
Типы для setState

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/model/requestHandler.ts
> +  const { method, url, headers, body } = DATA;
```suggestion
export const sendRequest = async ({ method, url, headers, body }: IRequestData) => {
```

Кроме того можнно поправить пропсы:
```suggestion
export const sendRequest = async ({ method, url, headers, data}: IRequestData) => {
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/model/bodyManagerModel.ts
> +  setBody: (value: (prev: IBodyData | null) => IBodyData | null) => void;
![image](https://github.com/user-attachments/assets/feafcec0-ac2d-4227-ba62-d9f9ef794391)

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/model/requestHandler.ts
> +      data: body,
И если исправить пропсы то:
```suggestion
      data,
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/BodyManager.tsx
> +  const { body, setBody } = props;
```suggestion
const BodyManager = ({ body, setBody }: IBodyProps) => {
```

Или:
```suggestion
const BodyManager: FC<IBodyProps> = ({ body, setBody }) => {
```

Зависит от code style.
По хорошему JSDoc

```suggestion
/**
* Description
*/
const BodyManager = (props: IBodyProps) => {
  const { body, setBody } = props;
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/BodyManager.tsx
> +  };
```suggestion
  const handleTextChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    const { value } = e?.target || {};
    
    if (!value) {
      return
    }
    
    setTextBody(value);
    
    try {
      const parsed = JSON.parse(value);
      
      setBody(parsed);
      setError(null);
    } catch (err) {
      setBody(() => null);
      setError('Invalid JSON');
    }
  };
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/BodyManager.tsx
> +  );
```suggestion
  const [textBody, setTextBody] = useState<string>(() => JSON.stringify(body ?? '', null, 2));
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/BodyManager.tsx
> +    <>
```suggestion
    
```
Box используется

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/BodyManager.tsx
> +          onChange={handleTextChange}
Если речь идет о JSON я бы называл по принципу что он ожидает

const [json, setJson]

handleTextChange просто handleChange

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/HeaderManager.tsx
> +  const { setHeaders } = props;
Тоже самое с пропсами/типами/JSDoc

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/HeaderManager.tsx
> +  const createHeader = () => {
```suggestion
  const createHeader = (): void => {
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/MethodManager.tsx
> +  const { method, setMethod } = props;
Пропсы/типы/JSDoc

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/MethodManager.tsx
> +        onChange={(e) => setMethod(e.target.value as ICRUD)}
В отдельную функицю как уже было выше:
`const handleTextChange = (e: React.ChangeEvent<HTMLInputElement>) => {`

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/OneHeaderElement.tsx
> +
```suggestion
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/OneHeaderElement.tsx
> +import { Box, Button, TextField } from '@mui/material';
```suggestion
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
```

Это на свое усмотрение. Такой импорт просто уменьшает финальный бандл. Точно такая же история с импортом lodash

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/OneHeaderElement.tsx
> +  const { id, items, setItems } = props;
Пропсы/типы/jsdoc

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/OneHeaderElement.tsx
> +  });
Лучше все валидационные схемы выносить отдельно в папку `validations`

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/RestFullClient.tsx
> +
```suggestion
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/RestFullClient.tsx
> +
```suggestion
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/RestFullClient.tsx
> +      body: body,
```suggestion
      method,
      url,
      headers,
      body,
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/RestFullClient.tsx
> +        );
```suggestion
   const isSuccessfull = response?.status < 300
   
   dispatch(
          showAlert({
            alert: true,
            style: isSuccessfull ? AlertStyle.success : AlertStyle.error,
            alertText: isSuccessfull ? 'Request completed successfully !' : 'Request is failed ...',
          }),
        )
 
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +const encodeBase64 = (data: string) => {
JSDoc
Return type

Если это хэлпер - то вынести

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +  const { url, setUrl, method, headers, body } = props;
Пропсы/типы/JSDoc

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +    const encodedBody = body ? encodeBase64(JSON.stringify(body)) : '';
```suggestion
    const encodedBody = encodeBase64(JSON.stringify(body ?? ''));
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +    return `/${method}${encodedBody ? '/' + encodedBody : ''}${queryParams.toString() ? '?' + queryParams.toString() : ''}`;
Попробуй так

```
 `/${method}${encodedBody ? `/${encodedBody}` : ''}${queryParams?.toString() ? `?${queryParams.toString()}` : ''}`;
```

2024-09-06 09:21 UTC, imdimasan commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +        onChange={(e) => setUrl(e.target.value)}
Отдельной функией как было выше

2024-09-06 15:26 UTC, SkarabeyDM commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +const encodeBase64 = (data: string) => {
@mikhaelHan если что, хелперы в сегмент `lib`

2024-09-06 15:29 UTC, SkarabeyDM commented on src/widgets/restFullClient/ui/OneHeaderElement.tsx
> +import { Box, Button, TextField } from '@mui/material';
Предлагаю вместо этого поставить `babel`

2024-09-06 15:32 UTC, SkarabeyDM commented on src/widgets/restFullClient/model/headerManagerModel.ts
> +  setHeaders: (value: IHeaderData) => void;
@mikhaelHan переименуй этот интерфейс в `IHeadersProps`

2024-09-06 17:15 UTC, SkarabeyDM requested changes
Почему роут не добавил? Есть какая-то причина его не добавлять?

2024-09-08 15:29 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +        onChange={(e) => setUrl(e.target.value)}
вынес

2024-09-08 15:29 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +    return `/${method}${encodedBody ? '/' + encodedBody : ''}${queryParams.toString() ? '?' + queryParams.toString() : ''}`;
исправил

2024-09-08 15:29 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +    const encodedBody = body ? encodeBase64(JSON.stringify(body)) : '';
у нас в body (если боди пустой) приходит null, и с такой реализацией в URL попадает: /GET/IiI=, а нужно: /GET

2024-09-08 15:30 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +  const { url, setUrl, method, headers, body } = props;
исправил

2024-09-08 15:30 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +const encodeBase64 = (data: string) => {
вынес

2024-09-08 15:30 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/RestFullClient.tsx
> +        );
исправил

2024-09-08 15:30 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/RestFullClient.tsx
> +      body: body,
исправил

2024-09-08 15:30 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/RestFullClient.tsx
> +
убрал

2024-09-08 15:30 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/RestFullClient.tsx
> +
убрал

2024-09-08 15:30 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/OneHeaderElement.tsx
> +  });
сделал отдельным файлом

2024-09-08 15:30 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/OneHeaderElement.tsx
> +  const { id, items, setItems } = props;
исправил

2024-09-08 15:30 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/MethodManager.tsx
> +        onChange={(e) => setMethod(e.target.value as ICRUD)}
вынес в отдельную функцию

2024-09-08 15:30 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/MethodManager.tsx
> +  const { method, setMethod } = props;
исправил

2024-09-08 15:30 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/HeaderManager.tsx
> +  const createHeader = () => {
исправил

2024-09-08 15:30 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/HeaderManager.tsx
> +  const { setHeaders } = props;
исправил

2024-09-08 15:31 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/BodyManager.tsx
> +          onChange={handleTextChange}
исправил

2024-09-08 15:31 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/BodyManager.tsx
> +    <>
убрал

2024-09-08 15:31 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/BodyManager.tsx
> +  );
исправил так: const [textBody, setTextBody] = useState<string>(() =>
    !body ? '' : JSON.stringify(body),
  );
так как нужно чтоб появлялся placeholder с подсказкой, для этого нам нужна возможность диспатчить пустую строку

2024-09-08 15:31 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/BodyManager.tsx
> +  };
исправил

2024-09-08 15:31 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/BodyManager.tsx
> +  const { body, setBody } = props;
исправил

2024-09-08 15:31 UTC, mikhaelHan commented on src/widgets/restFullClient/model/requestHandler.ts
> +      data: body,
исправил

2024-09-08 15:31 UTC, mikhaelHan commented on src/widgets/restFullClient/model/requestHandler.ts
> +  const { method, url, headers, body } = DATA;
исправил

2024-09-08 15:31 UTC, mikhaelHan commented on src/widgets/restFullClient/model/methodManagerModel.ts
> +  setMethod: (value: ICRUD) => void;
исправил

2024-09-08 15:31 UTC, mikhaelHan commented on src/widgets/restFullClient/model/headerManagerModel.ts
> +  setItems: (value: (prev: IHeaderItem[]) => IHeaderItem[]) => void;
исправил

2024-09-08 15:31 UTC, mikhaelHan commented on src/widgets/restFullClient/model/headerManagerModel.ts
> +  setHeaders: (value: IHeaderData) => void;
исправил

2024-09-08 15:31 UTC, mikhaelHan commented on src/widgets/restFullClient/model/bodyManagerModel.ts
> +  setBody: (value: (prev: IBodyData | null) => IBodyData | null) => void;
исправил

2024-09-08 15:31 UTC, mikhaelHan commented on src/pages/HomePage/ui/HomePage.tsx
>  const HomePageComponent = () => {
исправил

2024-09-08 15:32 UTC, mikhaelHan commented on src/pages/HomePage/ui/HomePage.tsx
> +      <Grid></Grid>
убрал

2024-09-08 15:32 UTC, mikhaelHan commented on next.config.mjs
> +};
это нужно было, так как у меня в юзэфекте генерился 1 хедер при инициализации компонента. А в reactStrictMode: true, в dev режиме проходит 2 рендера и падают ошибки, так как ключи key в map одинаковые, ну и плюс 2 хедера появляется, а нужен один )). Но переписал логику и убрал  "reactStrictMode: false".

2024-09-09 13:26 UTC, imdimasan commented on src/widgets/restFullClient/ui/HeaderManager.tsx
> +        ))}
```suggestion
        {items.map(({id}: IHeadersItem) => (
          <OneHeaderElement key={id} id={id} setItems={setItems} />
        ))}
```

2024-09-09 13:26 UTC, imdimasan commented on src/widgets/restFullClient/ui/MethodManager.tsx
> +    setMethod(value as ICRUD);
Добавляй проверки на всякйи случай
```suggestion
  const handleChange = (e: SelectChangeEvent<string>): void => {
    const { value } = e?.target || {};
    
    if (!value) {
       return
    }
    
    setMethod(value as ICRUD);
```

2024-09-09 13:26 UTC, imdimasan commented on src/widgets/restFullClient/ui/MethodManager.tsx
> +        <MenuItem value={ICRUD.DELETE}>DELETE</MenuItem>
```suggestion
        {Object.values(ICRUD).map((crudValue) => (
        <MenuItem key={crudValue} value={crudValue}>
          {crudValue}
        </MenuItem>
      ))}
```

2024-09-09 13:26 UTC, imdimasan commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +  };
Тоже проверочку добавь на target

2024-09-09 13:49 UTC, mikhaelHan commented on src/shared/tests/__tests__/BodyManager.test.tsx
> +describe('BodyManager component', () => {
добавил JSDoc

2024-09-09 13:49 UTC, mikhaelHan commented on src/shared/tests/__tests__/HeaderManager.test.tsx
> +describe('HeaderManager component', () => {
добавил JSDoc

2024-09-09 13:49 UTC, mikhaelHan commented on src/shared/tests/__tests__/MethodManager.test.tsx
> +describe('MethodManager component', () => {
добавил JSDoc

2024-09-09 13:51 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/OneHeaderElement.tsx
> +
убрал

2024-09-09 13:55 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/HeaderManager.tsx
> +        ))}
исправил

2024-09-09 14:16 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/MethodManager.tsx
> +        <MenuItem value={ICRUD.DELETE}>DELETE</MenuItem>
исправил

2024-09-09 14:18 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/UrlManager.tsx
> +  };
добавил

2024-09-09 14:19 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/MethodManager.tsx
> +    setMethod(value as ICRUD);
добавил проверку

2024-09-09 14:19 UTC, mikhaelHan commented on src/widgets/restFullClient/ui/HeaderManager.tsx
> +        ))}
исправил

2024-09-10 07:23 UTC, SkarabeyDM approved these changes

2024-09-10 07:49 UTC, merged